# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

import sys, datetime, time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QThread
from PyQt5.QtWidgets import QMainWindow, QApplication
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")  
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(779, 480)
        MainWindow.setWindowTitle("車聯網專題Demo視窗")
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border:2px;\n""border-radius:15px")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 781, 491))
        self.frame_10.setAutoFillBackground(False)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame = QtWidgets.QFrame(self.frame_10)
        self.frame.setGeometry(QtCore.QRect(20, 20, 741, 131))
        self.frame.setStyleSheet("background-color:rgb(230,230,230,200)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 381, 81))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(40)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(410, 30, 350, 81))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(990, 100, 1001, 131))
        self.frame_2.setStyleSheet("background-color:rgb(138,181,251)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 441, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(480, 10, 501, 111))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label_4.raise_()
        self.frame_2.raise_()
        self.frame_3 = QtWidgets.QFrame(self.frame_10)
        self.frame_3.setGeometry(QtCore.QRect(20, 160, 741, 131))
        self.frame_3.setStyleSheet("background-color:rgb(230,230,230,200)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(990, 100, 1001, 131))
        self.frame_4.setStyleSheet("background-color:rgb(138,181,251)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 441, 111))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(48)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(480, 10, 501, 111))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 501, 91))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(39)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(550, 40, 171, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(30)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(470, 60, 71, 31))
        self.label_15.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_15.setObjectName("label_15")
        self.frame_6 = QtWidgets.QFrame(self.frame_10)
        self.frame_6.setGeometry(QtCore.QRect(550, 300, 211, 161))
        self.frame_6.setStyleSheet("background-color:rgb(230,230,230,200)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 200, 71))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(28)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_7.setObjectName("label_7")
        self.frame_5 = QtWidgets.QFrame(self.frame_10)
        self.frame_5.setGeometry(QtCore.QRect(290, 300, 241, 161))
        self.frame_5.setStyleSheet("background-color:rgb(230,230,230,200)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 201, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_8.setObjectName("label_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setEnabled(True)
        self.frame_7.setGeometry(QtCore.QRect(40, 70, 61, 31))
        self.frame_7.setStyleSheet("background-color:rgb(255,0,0)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.frame_8.setStyleSheet("background-color:rgb(255,0,0)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setGeometry(QtCore.QRect(40, 120, 61, 31))
        self.frame_13.setStyleSheet("background-color:rgb(255,0,0)")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(30, 40, 61, 41))
        self.frame_14.setStyleSheet("background-color:rgb(255,0,0)")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(110, 60, 90, 51))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(24)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(110, 110, 90, 41))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(24)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_12.setObjectName("label_12")
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setGeometry(QtCore.QRect(20, 300, 251, 161))
        self.frame_9.setStyleSheet("background-color:rgb(230,230,230,200)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(255,255,255,0)")
        self.label_2.setObjectName("label_2")
        self.label_16 = QtWidgets.QLabel(self.frame_10)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.label_16.setStyleSheet("border:2px;\n""border-radius:20px")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("C:/Users/user/Desktop/true.jpg"))
        self.label_16.setObjectName("label_16")
        self.label_16.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.frame_9.raise_()

        self.clock_change = MyThread()
        self.clock_change.sec_changed_signal.connect(self.update)
        self.clock_change.start()

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def update(self, t):
        print(11)
        self.label_7.setText(QtCore.QCoreApplication.translate("MainWindow", str(t)))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("MainWindow", "目前時速："))
        self.label_4.setText(_translate("MainWindow", "299km/h"))
        self.label_5.setText(_translate("MainWindow", "目前時速："))
        self.label_6.setText(_translate("MainWindow", "0km/h"))
        self.label_9.setText(_translate("MainWindow", "目前時速："))
        self.label_10.setText(_translate("MainWindow", "0km/h"))
        self.label_13.setText(_translate("MainWindow", "救護車方位："))
        self.label_14.setText(_translate("MainWindow", "左前方"))
        self.label_15.setText(_translate("MainWindow", "箭頭圖片"))
        self.label.setText(_translate("MainWindow", "目前時間"))
        self.label_8.setText(_translate("MainWindow", "系統狀態"))
        self.label_11.setText(_translate("MainWindow", "GPS"))
        self.label_12.setText(_translate("MainWindow", "NET"))
        self.label_2.setText(_translate("MainWindow", "GPSINFO:"))
        self.label_7.setText(QtCore.QCoreApplication.translate("MainWindow","sss"))
        
        
class MyThread(QThread):  
  
  
    sec_changed_signal = QtCore.pyqtSignal(int) # 信号类型：int
    def __init__(self, sec=1000, parent=None):  
        super().__init__(parent)
        self.sec = sec # 默认1000秒
  
    def run(self):  
        for self.i in range(self.sec):
            self.sec_changed_signal.emit(self.i)  #发射信号
            time.sleep(1)


class clock(QThread):

    time_change = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)

    def run(self):
        while 1:
            print("123")
            t = datetime.datetime.now()
            self.time_change.emit(str(t))
            time.sleep(1)

class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)
        

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())